/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cypherstudios.booking.view;

import java.awt.Color;

/**
 *
 * @author Victor
 */
public class appIni extends javax.swing.JFrame {

    //Variables para el falso boton X cerrar
    int xMouse, yMouse;

    /**
     * Creates new form appIni
     */
    public appIni() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        btnBookingList = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        nameBooking = new javax.swing.JLabel();
        nameEvent = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        menuLeft = new javax.swing.JLabel();
        formTittle = new javax.swing.JLabel();
        formDesc = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        navItemBooking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        panelBackground.setBackground(new java.awt.Color(44, 44, 44));
        panelBackground.setMaximumSize(new java.awt.Dimension(800, 500));
        panelBackground.setMinimumSize(new java.awt.Dimension(800, 500));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBookingList.setBackground(btnExit.getBackground());
        btnBookingList.setFont(btnExit.getFont());
        btnBookingList.setForeground(new java.awt.Color(255, 255, 255));
        btnBookingList.setText("Ver Eventos");
        btnBookingList.setToolTipText("Lista los eventos contratados");
        btnBookingList.setBorder(btnExit.getBorder());
        btnBookingList.setNextFocusableComponent(btnExit);
        panelBackground.add(btnBookingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, -1));
        btnBookingList.getAccessibleContext().setAccessibleParent(this);

        btnBooking.setBackground(btnExit.getBackground());
        btnBooking.setFont(btnExit.getFont());
        btnBooking.setForeground(new java.awt.Color(255, 255, 255));
        btnBooking.setText("Reservar Evento");
        btnBooking.setToolTipText("Reservar Evento");
        btnBooking.setBorder(btnExit.getBorder());
        btnBooking.setNextFocusableComponent(btnBookingList);
        panelBackground.add(btnBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        btnBooking.getAccessibleContext().setAccessibleParent(this);

        nameBooking.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        nameBooking.setForeground(new java.awt.Color(160, 0, 0));
        nameBooking.setText("BOOKING");
        panelBackground.add(nameBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        nameEvent.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        nameEvent.setForeground(new java.awt.Color(255, 0, 0));
        nameEvent.setText("EVENTS");
        panelBackground.add(nameEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cypherstudios/booking/resources/logo-circle-100x100.png"))); // NOI18N
        imgLogo.setToolTipText("");
        panelBackground.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 100));

        menuLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cypherstudios/booking/resources/img-bg-dark.jpg"))); // NOI18N
        menuLeft.setMaximumSize(new java.awt.Dimension(420, 500));
        menuLeft.setMinimumSize(new java.awt.Dimension(420, 500));
        menuLeft.setPreferredSize(new java.awt.Dimension(420, 500));
        panelBackground.add(menuLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 500));

        formTittle.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        formTittle.setText("ORGANIZA TU EVENTO");

        formDesc.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        formDesc.setText("<html><p style=\\\"width:100%\\\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sapien neque, sodales vehicula faucibus in, porta eu mauris. In nec mollis nunc, vitae euismod libero. Morbi elementum urna neque, ut porttitor risus aliquam at. Donec venenatis nunc sed condimentum aliquet. Mauris est risus, consequat id urna eu, iaculis hendrerit ipsum. Nulla non massa vel felis pretium euismod sit amet sed libero.</p></html>");
        formDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnExit.setForeground(nameEvent.getForeground());
        btnExit.setText("SALIR");
        btnExit.setToolTipText("Cierra la aplicación");
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 30, 7, 30));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        pnlHeader.setPreferredSize(new java.awt.Dimension(40, 40));
        pnlHeader.setRequestFocusEnabled(false);
        pnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderMouseDragged(evt);
            }
        });
        pnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderMousePressed(evt);
            }
        });
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitTxt.setBackground(getBackground());
        exitTxt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        exitTxt.setForeground(nameEvent.getForeground());
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setToolTipText("Cerrar");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.setRequestFocusEnabled(false);
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });
        pnlHeader.add(exitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 0, -1, -1));

        navItemBooking.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        navItemBooking.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(navItemBooking)
                                            .addComponent(formTittle))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(48, 48, 48))
                    .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(navItemBooking)
                .addGap(36, 36, 36)
                .addComponent(formTittle)
                .addGap(18, 18, 18)
                .addComponent(formDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * Captura la posición del mouse en la pantalla
     *
     * @param evt
     */
    private void pnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlHeaderMousePressed

    /**
     * Hace que se pueda arrastrar la ventana con el mouse
     *
     * @param evt
     */
    private void pnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMouseDragged
        //Capturamos las posicion del mouse en la pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        //Posiciona la ventana en las coordenadas del mouse
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pnlHeaderMouseDragged

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        //exitTxt.setBackground(new Color(255, 0, 0));
        exitTxt.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        //exitTxt.setBackground(new Color(60,63,65));
        exitTxt.setBackground(getBackground());
        exitTxt.setForeground(nameEvent.getForeground());
    }//GEN-LAST:event_exitTxtMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(appIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(appIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(appIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(appIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new appIni().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBooking;
    public javax.swing.JButton btnBookingList;
    public javax.swing.JButton btnExit;
    public javax.swing.JLabel exitTxt;
    private javax.swing.JLabel formDesc;
    private javax.swing.JLabel formTittle;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel menuLeft;
    private javax.swing.JLabel nameBooking;
    private javax.swing.JLabel nameEvent;
    public javax.swing.JLabel navItemBooking;
    private javax.swing.JPanel panelBackground;
    public javax.swing.JPanel pnlHeader;
    // End of variables declaration//GEN-END:variables
}
