/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cypherstudios.booking.view;

import java.awt.*;

/**
 *
 * @author Victor
 */
public class Init extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Init() {
        initComponents();

        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("c-ico.png"));
        setIconImage(iconoPropio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgDecorationLeft = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnBookingList = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        navBar = new javax.swing.JMenuBar();
        navItem = new javax.swing.JMenu();
        navItemBooking = new javax.swing.JMenuItem();
        navItemBookingList = new javax.swing.JMenuItem();
        navItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        imgDecorationLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cypherstudios/booking/resources/img-decoration-left.jpg"))); // NOI18N

        btnExit.setBackground(new java.awt.Color(0, 102, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");
        btnExit.setToolTipText("Salir");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnBookingList.setText("Ver Reservas");
        btnBookingList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBookingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingListActionPerformed(evt);
            }
        });

        btnBooking.setText("Hacer Reserva");
        btnBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });

        navBar.setBackground(new java.awt.Color(102, 0, 102));
        navBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        navBar.setForeground(new java.awt.Color(255, 255, 255));
        navBar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        navItem.setBackground(navBar.getBackground());
        navItem.setBorder(navBar.getBorder());
        navItem.setForeground(navBar.getForeground());
        navItem.setText("Archivo");
        navItem.setToolTipText("");
        navItem.setFont(navBar.getFont());

        navItemBooking.setBackground(navBar.getBackground());
        navItemBooking.setFont(navItem.getFont());
        navItemBooking.setForeground(navBar.getForeground());
        navItemBooking.setText("Reservar");
        navItemBooking.setBorder(navItem.getBorder());
        navItem.add(navItemBooking);
        navItemBooking.getAccessibleContext().setAccessibleParent(navItem);

        navItemBookingList.setBackground(navBar.getBackground());
        navItemBookingList.setFont(navItem.getFont());
        navItemBookingList.setForeground(navBar.getForeground());
        navItemBookingList.setText("Ver Reservas");
        navItemBookingList.setBorder(navItem.getBorder());
        navItem.add(navItemBookingList);
        navItemBookingList.getAccessibleContext().setAccessibleParent(navItem);

        navItemExit.setBackground(navBar.getBackground());
        navItemExit.setFont(navItem.getFont());
        navItemExit.setForeground(navBar.getForeground());
        navItemExit.setText("Salir");
        navItemExit.setBorder(navItem.getBorder());
        navItem.add(navItemExit);
        navItemExit.getAccessibleContext().setAccessibleParent(navItem);

        navBar.add(navItem);

        setJMenuBar(navBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnBookingList, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgDecorationLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnBooking)
                .addGap(44, 44, 44)
                .addComponent(btnBookingList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgDecorationLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBookingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingListActionPerformed

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Init().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBooking;
    public javax.swing.JButton btnBookingList;
    public javax.swing.JButton btnExit;
    private javax.swing.JLabel imgDecorationLeft;
    public javax.swing.JMenuBar navBar;
    public javax.swing.JMenu navItem;
    public javax.swing.JMenuItem navItemBooking;
    public javax.swing.JMenuItem navItemBookingList;
    public javax.swing.JMenuItem navItemExit;
    // End of variables declaration//GEN-END:variables
}
